# Generated by Django 2.0.5 on 2020-01-15 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('rezyser', models.CharField(max_length=20)),
                ('cena', models.IntegerField()),
                ('data_premiery', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('pesel', models.IntegerField()),
                ('znizka', models.IntegerField()),
                ('nr_telefonu', models.IntegerField()),
                ('adress', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Magazyn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField()),
                ('nazwa_filmu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filmy.Film')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazyns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('pesel', models.CharField(max_length=11)),
                ('znizka', models.IntegerField()),
                ('nr_telefonu', models.IntegerField()),
                ('adress', models.CharField(max_length=200)),
                ('stanowisko', models.CharField(max_length=200)),
                ('wyplata', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pracownicys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField()),
                ('data_zwrotu', models.DateField()),
                ('data_wypozyczenia', models.DateField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filmy.Film')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filmy.Klient')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamowienies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
