# Generated by Django 2.0.5 on 2020-01-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=20)),
                ('cena', models.IntegerField()),
                ('data_premiery', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('pesel', models.IntegerField()),
                ('znizka', models.IntegerField()),
                ('nr_telefonu', models.IntegerField()),
                ('adress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Magazyn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_filmu', models.CharField(max_length=50)),
                ('ilosc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('pesel', models.CharField(max_length=11)),
                ('znizka', models.IntegerField()),
                ('nr_telefonu', models.IntegerField()),
                ('adress', models.CharField(max_length=200)),
                ('stanowisko', models.CharField(max_length=200)),
                ('wyplata', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(max_length=50)),
                ('klient', models.CharField(max_length=200)),
                ('ilosc', models.IntegerField()),
                ('data_zwrotu', models.DateField()),
                ('data_wypozyczenia', models.DateField()),
            ],
        ),
    ]
